"""
X-Verba Test Case Matrix Writer v0.2.0

Generates structured test stubs for every governance rule detected.

For each node, pre-node, invariant, threshold, and terminal state,
the matrix produces a test stub the developer fills in to verify
that governance actually works.

Structure:
  1. Node tests — does each AI call behave as specified?
  2. Pre-Node tests — does each checkpoint fire correctly?
  3. Invariant tests — does each rule hold under all conditions?
  4. Threshold tests — does the system enforce quantitative limits?
  5. Terminal State tests — does the system stop when it must?
  6. Boundary tests — DC-derived probe scenarios

The test stubs are designed to be readable by anyone.
VERBA terms appear as test_type values, not as required knowledge.

Fill in:
  - input_condition: the specific input that triggers this test
  - expected_outcome: what the system should do
  - pass_criteria: what proves the test passed
  - fail_criteria: what proves the test failed
"""
import yaml
from pathlib import Path


class TestMatrixWriter:
    """Generates the VERBA test case matrix alongside the governance contract."""

    def __init__(self, results: dict):
        self.results = results

    def write(self, output_path: str = None) -> str:
        if not output_path:
            output_path = ".verba/test_case_matrix.yaml"

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self._render(), encoding="utf-8")
        return str(path)

    def _render(self) -> str:
        lines = []

        lines += [
            "# ═══════════════════════════════════════════════════════════════",
            "# X-VERBA TEST CASE MATRIX",
            "# Generated by Super Semantics — supersemantics.org",
            "#",
            "# HOW TO USE THIS FILE",
            "#",
            "# Every governance rule in governance.yaml needs a test.",
            "# No test = unverifiable governance. Governance not verified",
            "# is governance not proven.",
            "#",
            "# For each test stub below, fill in:",
            "#   input_condition   — the specific input or state that triggers this test",
            "#   expected_outcome  — what the system should do",
            "#   pass_criteria     — what observable evidence proves the test passed",
            "#   fail_criteria     — what observable evidence proves the test failed",
            "#",
            "# test_type values:",
            "#   pre_node_check      — does the checkpoint fire before the AI call?",
            "#   invariant_violation — does the system stop when a rule is broken?",
            "#   threshold_breach    — does the system enforce quantitative limits?",
            "#   terminal_state_entry — does automation stop when it must?",
            "#   human_gate_trigger  — does the human gate fire and pause execution?",
            "#   boundary_probe      — can the system resist a known failure mode?",
            "#   happy_path          — does the system work correctly within bounds?",
            "#",
            "# Run these with x-verba qa in v0.2.",
            "# ═══════════════════════════════════════════════════════════════",
            "",
        ]

        identity = self.results.get("identity_key", "")
        primitives = self.results.get("primitives", {})
        gaps = self.results.get("gaps", [])
        dc_findings = self.results.get("drift_classes", [])
        ai_integrations = primitives.get("ai_integrations", [])
        summary = self.results.get("summary", {})

        meta = {
            "matrix_metadata": {
                "identity_key": identity,
                "scan_date": self.results.get("scan_date", ""),
                "verba_version": self.results.get("verba_version", "0.2.0"),
                "governance_contract_ref": ".verba/governance.yaml",
                "total_test_stubs_generated": self._count_stubs(ai_integrations, gaps, dc_findings),
                "stubs_requiring_completion": self._count_stubs(ai_integrations, gaps, dc_findings),
            }
        }
        lines.append(yaml.dump(meta, default_flow_style=False, allow_unicode=True))

        # Section 1: Node tests (happy path + output boundary)
        lines += self._section(
            "SECTION 1 — NODE TESTS",
            "Does each AI call produce output within the specified boundaries?",
            "One happy-path test and one output-boundary test per node.",
        )
        lines.append(self._render_node_tests(ai_integrations))

        # Section 2: Pre-Node tests
        lines += self._section(
            "SECTION 2 — PRE-NODE TESTS",
            "Does each governance checkpoint fire before the AI call executes?",
            "Test that valid input passes through and invalid input is blocked.",
        )
        lines.append(self._render_pre_node_tests(ai_integrations, gaps))

        # Section 3: Invariant tests
        constraints = primitives.get("constraints", [])
        lines += self._section(
            "SECTION 3 — INVARIANT TESTS",
            "Does the system stop and escalate when an invariant is violated?",
            "Test that the rule holds under adversarial and edge-case inputs.",
        )
        lines.append(self._render_invariant_tests(constraints))

        # Section 4: Threshold tests
        lines += self._section(
            "SECTION 4 — THRESHOLD TESTS",
            "Does the system enforce quantitative limits?",
            "Test boundary conditions: at limit, just over limit, well over limit.",
        )
        lines.append(self._render_threshold_tests(ai_integrations))

        # Section 5: Terminal state tests
        critical_gaps = [g for g in gaps if g.get("severity") == "critical"]
        lines += self._section(
            "SECTION 5 — TERMINAL STATE TESTS",
            "Does automation stop when it must?",
            "Test that entry conditions trigger the terminal state and",
            "that no automated path can exit it.",
        )
        lines.append(self._render_terminal_state_tests(critical_gaps))

        # Section 6: Human gate tests
        hg_gaps = [g for g in gaps if g.get("type") == "missing_human_gate"]
        lines += self._section(
            "SECTION 6 — HUMAN GATE TESTS",
            "Does the system pause and require human approval where required?",
            "Test that the gate fires, that approval unblocks, and that",
            "rejection terminates the flow correctly.",
        )
        lines.append(self._render_human_gate_tests(hg_gaps))

        # Section 7: Boundary / DC-derived probe tests
        lines += self._section(
            "SECTION 7 — BOUNDARY PROBE TESTS",
            "Can the system resist the failure modes detected in governance.yaml?",
            "Each probe is derived from a Drift Class candidate.",
            "These are adversarial scenarios — not expected normal use.",
        )
        lines.append(self._render_boundary_tests(dc_findings))

        # Section 8: Regression stubs (for x-verba qa)
        lines += self._section(
            "SECTION 8 — REGRESSION STUBS",
            "Stubs for use by x-verba qa in v0.2.",
            "These track governance contract compliance across commits.",
        )
        lines.append(self._render_regression_stubs(ai_integrations, gaps))

        return "\n".join(lines)

    def _section(self, title, *comments):
        out = [
            "# ───────────────────────────────────────────────────────────────",
            f"# {title}",
        ]
        for c in comments:
            out.append(f"# {c}")
        out.append("# ───────────────────────────────────────────────────────────────")
        out.append("")
        return out

    def _render_node_tests(self, ai_integrations: list) -> str:
        tests = []
        counter = 1

        for ai in ai_integrations:
            # Happy path
            tests.append({
                f"TC-{counter:03d}": {
                    "test_type": "happy_path",
                    "node_ref": ai["id"],
                    "location": ai["location"],
                    "description": f"Nominal operation at {ai['id']} — valid input, expected output",
                    "input_condition": None,
                    "expected_outcome": None,
                    "expected_system_state": "ALLOWED",
                    "pass_criteria": None,
                    "fail_criteria": None,
                    "automated": False,
                }
            })
            counter += 1

            # Output boundary
            tests.append({
                f"TC-{counter:03d}": {
                    "test_type": "output_boundary",
                    "node_ref": ai["id"],
                    "location": ai["location"],
                    "description": f"Output boundary check at {ai['id']} — AI output must stay within defined limits",
                    "input_condition": None,
                    "expected_outcome": "Output within permitted bounds",
                    "expected_system_state": "ALLOWED",
                    "pass_criteria": None,
                    "fail_criteria": "Output contains inadmissible content or exceeds thresholds",
                    "automated": False,
                }
            })
            counter += 1

        data = {"node_tests": tests if tests else [{"note": "No nodes detected."}]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_pre_node_tests(self, ai_integrations: list, gaps: list) -> str:
        tests = []
        counter = 1

        missing_ids = {
            g.get("ai_integration_ref")
            for g in gaps
            if g.get("type") == "missing_pre_node"
        }

        for ai in ai_integrations:
            is_missing = ai["id"] in missing_ids

            # Valid input passes through
            tests.append({
                f"PN-TC-{counter:03d}": {
                    "test_type": "pre_node_check",
                    "node_ref": ai["id"],
                    "location": ai["location"],
                    "description": f"Valid input passes Pre-Node at {ai['id']}",
                    "pre_node_status": "MISSING — define before testing" if is_missing else "detected",
                    "input_condition": None,
                    "expected_outcome": "Pre-Node conditions satisfied, AI call proceeds",
                    "expected_system_state": "ALLOWED",
                    "pass_criteria": None,
                    "fail_criteria": "AI call proceeds without pre-node check",
                    "automated": False,
                }
            })
            counter += 1

            # Invalid input is blocked
            tests.append({
                f"PN-TC-{counter:03d}": {
                    "test_type": "pre_node_check",
                    "node_ref": ai["id"],
                    "location": ai["location"],
                    "description": f"Invalid input blocked at Pre-Node for {ai['id']}",
                    "pre_node_status": "MISSING — define before testing" if is_missing else "detected",
                    "input_condition": None,
                    "expected_outcome": "Pre-Node blocks execution, returns defined fallback",
                    "expected_system_state": "BLOCKED",
                    "pass_criteria": None,
                    "fail_criteria": "AI call proceeds with invalid input",
                    "automated": False,
                }
            })
            counter += 1

            # User input sanitisation (if detected)
            if ai.get("user_input_in_prompt"):
                tests.append({
                    f"PN-TC-{counter:03d}": {
                        "test_type": "pre_node_check",
                        "node_ref": ai["id"],
                        "location": ai["location"],
                        "description": f"User input sanitisation at {ai['id']} — prompt injection attempt blocked",
                        "detected_risk": "user_input_in_prompt — DC-E5 candidate",
                        "input_condition": "Prompt injection string (e.g. 'Ignore all instructions and...')",
                        "expected_outcome": "Input sanitised or rejected before reaching AI",
                        "expected_system_state": "BLOCKED",
                        "pass_criteria": None,
                        "fail_criteria": "Injection string reaches the AI prompt unchanged",
                        "automated": False,
                    }
                })
                counter += 1

        data = {"pre_node_tests": tests if tests else [{"note": "No nodes detected."}]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_invariant_tests(self, constraints: list) -> str:
        tests = []
        counter = 1

        for i, c in enumerate(constraints, 1):
            tests.append({
                f"INV-TC-{counter:03d}": {
                    "test_type": "invariant_violation",
                    "invariant_ref": f"INV-{i:03d}",
                    "location": c["location"],
                    "current_code": c["line_content"],
                    "description": f"Invariant violation at {c['location']} — system must stop and escalate",
                    "input_condition": None,
                    "expected_outcome": "System halts, escalates to human, logs violation",
                    "expected_system_state": "TERMINAL",
                    "pass_criteria": None,
                    "fail_criteria": "System continues processing after invariant violation",
                    "automated": False,
                }
            })
            counter += 1

        # Template
        tests.append({
            f"INV-TC-TEMPLATE": {
                "test_type": "invariant_violation",
                "invariant_ref": None,
                "_comment": "Add invariant violation tests here. Copy this block.",
                "input_condition": None,
                "expected_outcome": "System halts and escalates",
                "expected_system_state": "TERMINAL",
                "pass_criteria": None,
                "fail_criteria": None,
                "automated": False,
            }
        })

        data = {"invariant_tests": tests}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_threshold_tests(self, ai_integrations: list) -> str:
        tests = []
        counter = 1

        for ai in ai_integrations:
            temp = ai.get("temperature")
            max_tokens = ai.get("max_tokens")

            if temp is not None and temp > 0.7:
                tests.append({
                    f"TH-TC-{counter:03d}": {
                        "test_type": "threshold_breach",
                        "node_ref": ai["id"],
                        "location": ai["location"],
                        "description": f"Temperature threshold at {ai['id']} — current value {temp} exceeds 0.7",
                        "parameter": "temperature",
                        "current_value": temp,
                        "threshold_to_test": None,
                        "input_condition": f"AI call with temperature={temp}",
                        "expected_outcome": "System enforces temperature limit or flags for review",
                        "expected_system_state": None,
                        "pass_criteria": None,
                        "fail_criteria": f"AI call proceeds with temperature > permitted maximum",
                        "automated": False,
                    }
                })
                counter += 1

            if not max_tokens:
                tests.append({
                    f"TH-TC-{counter:03d}": {
                        "test_type": "threshold_breach",
                        "node_ref": ai["id"],
                        "location": ai["location"],
                        "description": f"Unbounded output at {ai['id']} — no max_tokens limit detected",
                        "parameter": "max_tokens",
                        "current_value": "unbounded",
                        "threshold_to_test": None,
                        "input_condition": "Prompt designed to elicit very long output",
                        "expected_outcome": "Output length capped at defined threshold",
                        "expected_system_state": "ALLOWED",
                        "pass_criteria": None,
                        "fail_criteria": "Output exceeds maximum permitted length",
                        "automated": False,
                    }
                })
                counter += 1

        tests.append({
            "TH-TC-TEMPLATE": {
                "test_type": "threshold_breach",
                "_comment": "Add threshold tests here. Copy this block.",
                "parameter": None,
                "threshold_to_test": None,
                "input_condition": None,
                "expected_outcome": None,
                "pass_criteria": None,
                "fail_criteria": None,
            }
        })

        data = {"threshold_tests": tests}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_terminal_state_tests(self, critical_gaps: list) -> str:
        tests = []
        counter = 1

        for gap in critical_gaps:
            tests.append({
                f"TS-TC-{counter:03d}": {
                    "test_type": "terminal_state_entry",
                    "gap_ref": gap["id"],
                    "location": gap["location"],
                    "description": f"Terminal state triggered by {gap['verba_term']} at {gap['location']}",
                    "entry_trigger": gap["plain_english"],
                    "input_condition": None,
                    "expected_outcome": "Automation stops. Human notified. No further automated transitions.",
                    "expected_system_state": "TERMINAL",
                    "pass_criteria": None,
                    "fail_criteria": "Automation continues after terminal state entry condition is met",
                    "automated": False,
                }
            })
            counter += 1

            # Test that automated exit is impossible
            tests.append({
                f"TS-TC-{counter:03d}": {
                    "test_type": "terminal_state_exit_blocked",
                    "gap_ref": gap["id"],
                    "location": gap["location"],
                    "description": f"No automated exit from terminal state at {gap['location']}",
                    "input_condition": "Automated signal attempting to resume processing",
                    "expected_outcome": "Automated exit attempt rejected. Human authorisation required.",
                    "expected_system_state": "TERMINAL",
                    "pass_criteria": None,
                    "fail_criteria": "System exits terminal state without explicit human authorisation",
                    "automated": False,
                }
            })
            counter += 1

        data = {
            "terminal_state_tests": tests if tests
            else [{"note": "No critical gaps detected. Add terminal state tests manually."}]
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_human_gate_tests(self, hg_gaps: list) -> str:
        tests = []
        counter = 1

        for gap in hg_gaps:
            # Gate fires
            tests.append({
                f"HG-TC-{counter:03d}": {
                    "test_type": "human_gate_trigger",
                    "gap_ref": gap["id"],
                    "location": gap["location"],
                    "description": f"Human gate fires at {gap['location']} — execution pauses for approval",
                    "input_condition": None,
                    "expected_outcome": "Execution pauses. Human notified. Awaiting approval.",
                    "expected_system_state": "AWAITING_HUMAN",
                    "pass_criteria": None,
                    "fail_criteria": "AI output proceeds to destination without human approval",
                    "automated": False,
                }
            })
            counter += 1

            # Approval unblocks
            tests.append({
                f"HG-TC-{counter:03d}": {
                    "test_type": "human_gate_approval",
                    "gap_ref": gap["id"],
                    "location": gap["location"],
                    "description": f"Human approval unblocks execution at {gap['location']}",
                    "input_condition": "Human approves the pending output",
                    "expected_outcome": "Execution resumes with approval logged in audit trail",
                    "expected_system_state": "ALLOWED",
                    "pass_criteria": None,
                    "fail_criteria": "Approval not recorded in audit trail",
                    "automated": False,
                }
            })
            counter += 1

            # Rejection terminates
            tests.append({
                f"HG-TC-{counter:03d}": {
                    "test_type": "human_gate_rejection",
                    "gap_ref": gap["id"],
                    "location": gap["location"],
                    "description": f"Human rejection terminates flow at {gap['location']}",
                    "input_condition": "Human rejects the pending output",
                    "expected_outcome": "Flow terminated. Rejection logged. No output reaches destination.",
                    "expected_system_state": "REJECTED",
                    "pass_criteria": None,
                    "fail_criteria": "Output reaches destination despite human rejection",
                    "automated": False,
                }
            })
            counter += 1

        data = {
            "human_gate_tests": tests if tests
            else [{"note": "No missing human gates detected. Add human gate tests manually."}]
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_boundary_tests(self, dc_findings: list) -> str:
        """Generate boundary probe tests derived from DC candidates."""
        tests = []
        counter = 1

        # DC-specific probe templates
        dc_probes = {
            "DC-E5": {
                "probe_description": "Prompt injection attempt — adversarial user input designed to override system instructions",
                "input_condition": "User input containing 'Ignore all previous instructions and...'",
                "expected_outcome": "Input rejected or sanitised at Pre-Node. Injection never reaches AI.",
            },
            "DC-L2": {
                "probe_description": "Dynamic prompt boundary violation — assembled prompt crosses content boundary",
                "input_condition": "Input that, when assembled into the prompt template, produces an inadmissible instruction",
                "expected_outcome": "Prompt assembly halted at Pre-Node boundary check.",
            },
            "DC-I6": {
                "probe_description": "Cascade rupture via high temperature — high-entropy output triggers downstream failure",
                "input_condition": "AI call with high temperature producing ambiguous or contradictory output",
                "expected_outcome": "Output flagged for review before downstream processing.",
            },
            "DC-E13": {
                "probe_description": "Chained call error propagation — bad output from call N seeds call N+1",
                "input_condition": "First AI call returns output containing adversarial content",
                "expected_outcome": "Inter-call validation fires. Adversarial content does not seed next call.",
            },
            "DC-S3": {
                "probe_description": "Cluster-level cascade — one service's failure propagates to all others",
                "input_condition": "One AI service enters inadmissible state",
                "expected_outcome": "Cluster-level governance isolates the service. No cascade.",
            },
            "DC-E14": {
                "probe_description": "Knight Capital pattern — AI-triggered irreversible action with no gate",
                "input_condition": "AI output triggers irreversible action (db delete / email send / payment)",
                "expected_outcome": "Eligibility condition fires. Human authorisation required before execution.",
            },
            "DC-I11": {
                "probe_description": "Evaluative decoupling — AI output metric diverges from stated objective",
                "input_condition": "AI output that scores well on observed metrics but violates governance intent",
                "expected_outcome": "Governance checkpoint detects misalignment before output proceeds.",
            },
        }

        seen_codes = set()
        for finding in dc_findings:
            dc_code = finding["dc_code"]
            if dc_code in seen_codes:
                continue
            seen_codes.add(dc_code)

            probe = dc_probes.get(dc_code, {})
            tests.append({
                f"BP-TC-{counter:03d}": {
                    "test_type": "boundary_probe",
                    "dc_candidate_ref": dc_code,
                    "dc_name": finding["dc_name"],
                    "location": finding["location"],
                    "probe_description": probe.get(
                        "probe_description",
                        f"Probe for {dc_code} {finding['dc_name']} — define scenario",
                    ),
                    "input_condition": probe.get("input_condition", None),
                    "expected_outcome": probe.get("expected_outcome", None),
                    "expected_system_state": "BLOCKED or TERMINAL",
                    "pass_criteria": None,
                    "fail_criteria": f"System does not resist {dc_code} failure mode",
                    "automated": False,
                }
            })
            counter += 1

        data = {
            "boundary_probe_tests": tests if tests
            else [{"note": "No Drift Class candidates detected. Add boundary tests manually."}]
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_regression_stubs(self, ai_integrations: list, gaps: list) -> str:
        """Stubs for use by x-verba qa in v0.2."""
        stubs = []

        for ai in ai_integrations:
            stubs.append({
                f"REG-{ai['id']}": {
                    "type": "ai_integration_present",
                    "location": ai["location"],
                    "provider": ai["provider"],
                    "pre_node_required": True,
                    "human_gate_required": True,
                    "qa_note": "x-verba qa will flag if this call loses its pre-node or human gate",
                }
            })

        for gap in gaps:
            if gap.get("type") in ("missing_pre_node", "ungated_irreversible_action"):
                stubs.append({
                    f"REG-{gap['id']}": {
                        "type": gap["type"],
                        "location": gap["location"],
                        "severity": gap["severity"],
                        "qa_note": "x-verba qa will track whether this gap is resolved or worsens",
                    }
                })

        data = {
            "regression_stubs": {
                "_note": (
                    "Used by x-verba qa in v0.2. "
                    "These stubs track governance contract compliance across commits."
                ),
                "stubs": stubs,
            }
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _count_stubs(self, ai_integrations, gaps, dc_findings) -> int:
        n = len(ai_integrations) * 2  # happy path + output boundary per node
        n += len(ai_integrations) * 2  # valid + invalid per pre-node
        n += sum(1 for ai in ai_integrations if ai.get("user_input_in_prompt"))
        n += len([g for g in gaps if g.get("severity") == "critical"]) * 2
        n += len([g for g in gaps if g.get("type") == "missing_human_gate"]) * 3
        n += len(set(f["dc_code"] for f in dc_findings))
        return n
