"""
X-Verba Output Writer v0.2.0

Generates the VERBA governance contract — the developer-facing template
that defines what the system must and must never do.

Structure:
  1. System Identity
  2. Nodes (detected AI calls)
  3. Pre-Nodes (what must be checked before each node)
  4. Invariants (rules that must always hold)
  5. Thresholds (quantitative limits)
  6. Human Authorisation Gates
  7. Terminal States (where automation must stop)
  8. Drift Class Candidates (diagnostic context)
  9. Governance Score

Design principle: a developer who has never heard of VERBA should be able
to open this file, read the comments, and know exactly what to fill in.
VERBA terms appear as field names, not as required prior knowledge.

Plain English first. VERBA term second. Always.
"""
import json
import yaml
from pathlib import Path
from datetime import datetime, timezone


class OutputWriter:
    """Writes scan results as a VERBA governance contract."""

    def __init__(self, results: dict, output_format: str = "yaml"):
        self.results = results
        self.format = output_format.lower()

    def write(self, output_path: str = None) -> str:
        if not output_path:
            output_path = self._default_output_path()

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if self.format == "yaml":
            content = self._render_yaml()
        elif self.format == "json":
            content = self._render_json()
        elif self.format == "md":
            content = self._render_markdown()
        else:
            content = self._render_yaml()

        path.write_text(content, encoding="utf-8")
        return str(path)

    def _default_output_path(self) -> str:
        ext_map = {"yaml": "yaml", "json": "json", "md": "md"}
        ext = ext_map.get(self.format, "yaml")
        return f".verba/governance.{ext}"

    # ── YAML renderer ─────────────────────────────────────────────────────────

    def _render_yaml(self) -> str:
        lines = []

        lines += [
            "# ═══════════════════════════════════════════════════════════════",
            "# X-VERBA GOVERNANCE CONTRACT",
            "# Generated by Super Semantics — supersemantics.org",
            "#",
            "# HOW TO USE THIS FILE",
            "#",
            "# This is your system's governance contract.",
            "# X-Verba scanned your code and found the decision points.",
            "# Your job is to fill in every field marked: null",
            "#",
            "# Each section has plain-English instructions.",
            "# Fill in plain English first — Verba Studio will help you",
            "# translate it into formal policy.",
            "#",
            "# Fields left null will be flagged by x-verba qa.",
            "# ═══════════════════════════════════════════════════════════════",
            "",
        ]

        # System Identity
        lines += self._section(
            "SECTION 1 — SYSTEM IDENTITY",
            "Scope all governance events to this system.",
            "Fill in these fields once. They propagate through the full lifecycle.",
        )
        meta = {
            "system_identity": {
                "identity_key": self.results.get("identity_key", ""),
                "system_name": None,
                "version": None,
                "domain": None,
                "governance_authority": None,
                "scan_date": self.results.get("scan_date", ""),
                "verba_version": self.results.get("verba_version", "0.2.0"),
                "context_profile": self.results.get("context_profile", "ai-app"),
                "reviewed": False,
                "approved": False,
                "approved_by": None,
                "approved_date": None,
            }
        }
        lines.append(yaml.dump(meta, default_flow_style=False, allow_unicode=True))

        # Executive summary (read-only)
        summary = self.results.get("summary", {})
        lines += self._section(
            "SECTION 2 — SCAN SUMMARY",
            "What X-Verba found. Read-only — do not edit.",
        )
        lines.append(self._render_summary_yaml(summary))

        # Nodes
        primitives = self.results.get("primitives", {})
        lines += self._section(
            "SECTION 3 — NODES",
            "A Node is a point where your system makes a consequential decision.",
            "Every AI call is a Node. X-Verba detected these automatically.",
            "",
            "For each node, define:",
            "  - What it does (description)",
            "  - Where its input comes from (input_source)",
            "  - Where its output goes (output_destination)",
            "  - How critical it is (criticality: low / medium / high / critical)",
        )
        lines.append(self._render_nodes_yaml(primitives))

        # Pre-Nodes
        lines += self._section(
            "SECTION 4 — PRE-NODES",
            "A Pre-Node is the mandatory checkpoint that fires immediately before",
            "a Node executes. It is the last point where governance can stop",
            "the system before it commits.",
            "",
            "X-Verba detected these as MISSING where no checkpoint was found.",
            "For each one, define:",
            "  - What conditions must be TRUE for execution to proceed",
            "  - What conditions will BLOCK execution (and what happens next)",
            "  - What the fallback is if conditions are not met",
        )
        lines.append(self._render_pre_nodes_yaml(primitives, self.results.get("gaps", [])))

        # Invariants
        lines += self._section(
            "SECTION 5 — INVARIANTS",
            "An Invariant is a rule that must ALWAYS be true — across every state,",
            "every input, every transition. No exceptions. Cannot be bypassed.",
            "",
            "If violated, the system must stop and escalate to a human. Always.",
            "",
            "X-Verba detected these informal checks in your code as candidates.",
            "Formalise them here. Add any additional invariants you require.",
        )
        lines.append(self._render_invariants_yaml(primitives))

        # Thresholds
        lines += self._section(
            "SECTION 6 — THRESHOLDS",
            "A Threshold is a fixed quantitative limit your system cannot exceed.",
            "Exceeding a Threshold triggers a governance response.",
            "",
            "X-Verba detected these parameters from your AI calls.",
            "Set the permitted ranges. Define what happens when they are exceeded.",
        )
        lines.append(self._render_thresholds_yaml(primitives))

        # Human Authorisation Gates
        gaps = self.results.get("gaps", [])
        lines += self._section(
            "SECTION 7 — HUMAN AUTHORISATION GATES",
            "A Human Authorisation Gate is a point where automation must pause",
            "and a human must explicitly approve before the system continues.",
            "",
            "In VERBA: a Human-Authorised Transition cannot be initiated by automation.",
            "It requires explicit, auditable human approval.",
            "",
            "X-Verba detected these as MISSING — no human gate was found.",
        )
        lines.append(self._render_human_gates_yaml(gaps))

        # Terminal States
        lines += self._section(
            "SECTION 8 — TERMINAL STATES",
            "A Terminal State is a state from which no automated transition is permitted.",
            "Automation stops. A human must explicitly authorise the next step.",
            "Automation cannot exit a Terminal State. Ever.",
            "",
            "Define entry conditions for every critical gap below.",
        )
        lines.append(self._render_terminal_states_yaml(gaps))

        # DC Findings (diagnostic context, not the primary task)
        dc_findings = self.results.get("drift_classes", [])
        lines += self._section(
            "SECTION 9 — FAILURE MODE CANDIDATES",
            "Drift Classes are formally defined categories of failure mode.",
            "Think of them as diagnostic codes — like ICD codes for medical diagnosis.",
            "",
            "These are CANDIDATES — structural indicators detected in your code.",
            "Review and confirm each one. They inform the Invariants and Terminal States above.",
        )
        lines.append(self._render_dc_findings_yaml(dc_findings))

        # Gamma
        gamma = self.results.get("structural_gamma", {})
        lines += self._section(
            "SECTION 10 — GOVERNANCE SCORE",
            "Structural Gamma = Governed Decision Points / Total Decision Points",
            "Target: >= 0.9. Below 0.5 = structurally ungoverned.",
            "Note: this is a structural proxy, not runtime Gamma.",
        )
        lines.append(self._render_gamma_yaml(gamma))

        # Next steps
        lines += self._section("SECTION 11 — NEXT STEPS")
        lines.append(self._render_next_steps_yaml(summary, gaps))

        return "\n".join(lines)

    def _section(self, title, *lines):
        """Emit a section header block."""
        out = [
            "# ───────────────────────────────────────────────────────────────",
            f"# {title}",
        ]
        for line in lines:
            out.append(f"# {line}" if line else "#")
        out.append("# ───────────────────────────────────────────────────────────────")
        out.append("")
        return out

    def _render_summary_yaml(self, summary: dict) -> str:
        ai_count = summary.get("ai_integrations_detected", 0)
        critical = summary.get("critical", 0)
        high = summary.get("high", 0)
        medium = summary.get("medium", 0)
        files = summary.get("files_scanned", 0)
        gamma = summary.get("structural_gamma")
        status = summary.get("governance_status", "UNKNOWN")

        data = {
            "scan_summary": {
                "files_scanned": files,
                "ai_integrations_detected": ai_count,
                "findings": {
                    "critical": critical,
                    "high": high,
                    "medium": medium,
                    "total": critical + high + medium,
                },
                "structural_gamma_proxy": gamma,
                "governance_status": status,
            }
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_nodes_yaml(self, primitives: dict) -> str:
        ai_integrations = primitives.get("ai_integrations", [])
        nodes = []

        for ai in ai_integrations:
            nodes.append({
                ai["id"]: {
                    "detected_at": ai["location"],
                    "provider": ai.get("provider", "unknown"),
                    "line_content": ai.get("line_content", ""),
                    "streaming": ai.get("streaming", False),
                    # Fields for developer to fill in
                    "description": None,
                    "input_source": None,
                    "output_destination": ai.get("output_destination", None),
                    "criticality": None,
                    "notes": None,
                }
            })

        data = {"nodes": nodes if nodes else [{"note": "No AI integrations detected."}]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_pre_nodes_yaml(self, primitives: dict, gaps: list) -> str:
        ai_integrations = primitives.get("ai_integrations", [])
        pre_nodes = []

        missing_locs = {
            g["ai_integration_ref"]
            for g in gaps
            if g.get("type") == "missing_pre_node" and g.get("ai_integration_ref")
        }

        for ai in ai_integrations:
            status = "MISSING" if ai["id"] in missing_locs else "detected"
            entry = {
                f"PN-{ai['id']}": {
                    "node_ref": ai["id"],
                    "location": ai["location"],
                    "status": status,
                    "pre_node_detected_in_code": ai.get("pre_node_detected", False),
                    "user_input_in_prompt": ai.get("user_input_in_prompt", False),
                    "dynamic_prompt": ai.get("dynamic_prompt", False),
                    # Fields for developer to fill in
                    "conditions_that_must_be_true": None,
                    "conditions_that_block_execution": None,
                    "what_happens_on_block": None,
                    "input_sanitisation_required": None,
                    "prompt_boundary_defined": None,
                    "governance_log_on_entry": True,
                }
            }
            pre_nodes.append(entry)

        data = {"pre_nodes": pre_nodes if pre_nodes else [{"note": "No nodes detected."}]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_invariants_yaml(self, primitives: dict) -> str:
        constraints = primitives.get("constraints", [])
        invariants = []

        for i, c in enumerate(constraints, 1):
            invariants.append({
                f"INV-{i:03d}": {
                    "detected_from": c["location"],
                    "current_code": c["line_content"],
                    "constraint_type": c["type"],
                    "near_ai_call": c.get("near_ai_call", False),
                    "currently_enforced_in_code": True,
                    "currently_formalised": False,
                    # Fields for developer to fill in
                    "rule": None,
                    "scope": None,
                    "cannot_be_bypassed": True,
                    "violation_action": None,
                    "severity": None,
                    "audit_on_check": True,
                }
            })

        # Add blank template entries for additional invariants
        invariants.append({
            "INV-TEMPLATE": {
                "_comment": "Add your own invariants here. Copy this block.",
                "rule": None,
                "scope": None,
                "cannot_be_bypassed": True,
                "violation_action": None,
                "severity": None,
                "audit_on_check": True,
            }
        })

        data = {"invariants": invariants}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_thresholds_yaml(self, primitives: dict) -> str:
        ai_integrations = primitives.get("ai_integrations", [])
        thresholds = []

        for i, ai in enumerate(ai_integrations, 1):
            temp = ai.get("temperature")
            max_tokens = ai.get("max_tokens")

            if temp is not None or max_tokens is not None:
                thresholds.append({
                    f"TH-{i:03d}": {
                        "node_ref": ai["id"],
                        "location": ai["location"],
                        "detected_parameters": {
                            "temperature": {
                                "current_value": temp,
                                "risk": (
                                    f"HIGH — temperature {temp} increases output variability. "
                                    "Governance cost scales with temperature."
                                ) if temp and temp > 0.7 else (
                                    f"Within acceptable range ({temp})"
                                ) if temp is not None else "Not detected",
                            },
                            "max_tokens": {
                                "current_value": max_tokens,
                                "risk": (
                                    "Unbounded output length — no explicit limit detected."
                                ) if not max_tokens else f"Limited to {max_tokens} tokens",
                            },
                        },
                        # Fields for developer to fill in
                        "maximum_temperature_permitted": None,
                        "maximum_output_tokens": None,
                        "minimum_confidence_score": None,
                        "forbidden_content_patterns": None,
                        "on_threshold_breach": None,
                    }
                })

        thresholds.append({
            "TH-TEMPLATE": {
                "_comment": "Add quantitative thresholds here. Copy this block.",
                "parameter": None,
                "maximum_permitted": None,
                "minimum_permitted": None,
                "on_breach": None,
            }
        })

        data = {"thresholds": thresholds}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_human_gates_yaml(self, gaps: list) -> str:
        hg_gaps = [g for g in gaps if g.get("type") == "missing_human_gate"]
        gates = []

        for gap in hg_gaps:
            gates.append({
                gap["id"]: {
                    "location": gap["location"],
                    "ai_integration_ref": gap.get("ai_integration_ref", ""),
                    "status": "MISSING",
                    "output_flows_to": gap.get("plain_english", ""),
                    # Fields for developer to fill in
                    "trigger_condition": None,
                    "authorisation_level": None,
                    "what_human_must_review": None,
                    "what_human_must_approve": None,
                    "timeout_seconds": None,
                    "on_timeout": None,
                    "audit_trail_required": True,
                }
            })

        gates.append({
            "HG-TEMPLATE": {
                "_comment": "Add human authorisation gates here. Copy this block.",
                "trigger_condition": None,
                "authorisation_level": None,
                "what_human_must_approve": None,
                "timeout_seconds": None,
                "on_timeout": None,
                "audit_trail_required": True,
            }
        })

        data = {"human_authorisation_gates": gates}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_terminal_states_yaml(self, gaps: list) -> str:
        critical_gaps = [g for g in gaps if g.get("severity") == "critical"]
        ts_entries = []

        for i, gap in enumerate(critical_gaps, 1):
            ts_entries.append({
                f"TS-{i:03d}": {
                    "triggered_by_gap": gap["id"],
                    "location": gap["location"],
                    "reason": gap["plain_english"],
                    "automated_transitions": "NONE — by definition",
                    "human_authorised_exit_required": True,
                    "re_enablement_creates_new_instance": True,
                    # Fields for developer to fill in
                    "entry_conditions": None,
                    "governance_authority": None,
                    "escalation_path": None,
                    "response_time_sla": None,
                    "notification_targets": None,
                }
            })

        ts_entries.append({
            "TS-TEMPLATE": {
                "_comment": "Add terminal states here. Copy this block.",
                "entry_conditions": None,
                "automated_transitions": "NONE",
                "governance_authority": None,
                "escalation_path": None,
                "response_time_sla": None,
            }
        })

        data = {"terminal_states": ts_entries}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_dc_findings_yaml(self, dc_findings: list) -> str:
        finding_data = []

        for i, finding in enumerate(dc_findings, 1):
            contraindications = finding.get(
                "stabiliser_recommendation", {}
            ).get("contraindications", [])

            finding_data.append({
                f"DC-FINDING-{i:03d}": {
                    "code": finding["dc_code"],
                    "name": finding["dc_name"],
                    "tier": finding["tier"],
                    "location": finding["location"],
                    "severity": finding["severity"],
                    "plain_english": finding["plain_english"],
                    "what_happens_without_governance": finding.get(
                        "what_happens_without_governance", ""
                    ),
                    "evidence_detected": finding["evidence"],
                    "legion_detected": {
                        "code": finding["legion_detected"]["code"],
                        "name": finding["legion_detected"]["name"],
                    },
                    "stabiliser_recommendation": {
                        "operator": finding["stabiliser_recommendation"]["primary_so"],
                        "name": finding["stabiliser_recommendation"]["so_name"],
                        "contraindications": [
                            {
                                "do_not_apply": c.get("do_not_apply", ""),
                                "reason": c.get("reason", ""),
                            }
                            for c in contraindications
                        ] if contraindications else "None",
                    },
                    "monitoring_frequency": finding["monitoring_frequency"],
                    # Fields for developer to fill in
                    "confirmed": None,
                    "invariant_ref": None,
                    "terminal_state_ref": None,
                }
            })

        data = {
            "drift_class_candidates": finding_data if finding_data
            else [{"note": "No Drift Class candidates detected."}]
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_gamma_yaml(self, gamma: dict) -> str:
        data = {
            "structural_gamma": {
                "proxy_value": gamma.get("proxy_value"),
                "threshold": gamma.get("threshold", 0.9),
                "status": gamma.get("status", "UNKNOWN"),
                "interpretation": gamma.get("interpretation", ""),
                "total_decision_points": gamma.get("total_decision_points", 0),
                "governed_decision_points": gamma.get("governed_decision_points", 0),
                "note": gamma.get("important_note", ""),
            }
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_next_steps_yaml(self, summary: dict, gaps: list) -> str:
        critical = summary.get("critical", 0)
        steps = {
            "next_steps": [
                {
                    "step_1": {
                        "action": "Fill in every null field in this file",
                        "start_with": "Section 4 (Pre-Nodes) and Section 8 (Terminal States)",
                        "critical_count": critical,
                    }
                },
                {
                    "step_2": {
                        "action": "Complete the test stubs in test_case_matrix.yaml",
                        "why": "Every governance rule needs a test. No test = unverifiable governance.",
                    }
                },
                {
                    "step_3": {
                        "action": "Open in Verba Studio for AI-assisted authoring",
                        "url": "https://studio.supersemantics.org",
                    }
                },
                {
                    "step_4": {
                        "action": "Add x-verba qa to your CI/CD pipeline",
                        "command": "x-verba qa . --schema .verba/governance.yaml",
                        "note": "Coming in v0.2. Returns exit code 1 if critical regressions found.",
                    }
                },
                {
                    "step_5": {
                        "action": "Compile and deploy with VERBA Runtime",
                        "command": "x-verba compile .verba/governance.yaml",
                        "note": "Coming in v0.2.",
                    }
                },
            ]
        }
        return yaml.dump(steps, default_flow_style=False, allow_unicode=True)

    # ── JSON renderer ─────────────────────────────────────────────────────────

    def _render_json(self) -> str:
        return json.dumps(self.results, indent=2, default=str)

    # ── Markdown renderer ─────────────────────────────────────────────────────

    def _render_markdown(self) -> str:
        lines = []
        summary = self.results.get("summary", {})
        gaps = self.results.get("gaps", [])
        dc_findings = self.results.get("drift_classes", [])
        gamma = self.results.get("structural_gamma", {})

        lines.append("# X-Verba Governance Report")
        lines.append(
            f"*Generated {self.results.get('scan_date', '')} by Super Semantics*"
        )
        lines.append("")
        lines.append(
            f"**Repository:** `{self.results.get('repo', '')}`  "
        )
        lines.append(
            f"**Identity Key:** `{self.results.get('identity_key', '')}`  "
        )
        lines.append(
            f"**Context Profile:** `{self.results.get('context_profile', 'ai-app')}`"
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## What we found")
        lines.append("")

        ai_count = summary.get("ai_integrations_detected", 0)
        critical = summary.get("critical", 0)
        high = summary.get("high", 0)
        coverage = summary.get("governance_coverage", "N/A")
        gamma_val = summary.get("structural_gamma")
        files = summary.get("files_scanned", 0)

        lines.append(
            f"X-Verba scanned **{files} files** and found "
            f"**{ai_count} AI integration points**."
        )
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("| --- | --- |")
        lines.append(f"| Critical findings | **{critical}** |")
        lines.append(f"| High findings | {high} |")
        lines.append(f"| Governance coverage | {coverage} |")
        gamma_display = str(gamma_val) if gamma_val is not None else "N/A"
        lines.append(
            f"| Structural Gamma proxy | {gamma_display} "
            f"({'below threshold' if gamma_val is not None and gamma_val < 0.9 else 'N/A' if gamma_val is None else 'at threshold'}) |"
        )
        lines.append("")

        if critical > 0 or high > 0:
            lines.append("---")
            lines.append("")
            lines.append("## Governance gaps")
            lines.append("")
            for gap in gaps:
                if gap.get("severity") in ["critical", "high"]:
                    label = (
                        "🔴 CRITICAL" if gap["severity"] == "critical"
                        else "🟡 HIGH"
                    )
                    lines.append(f"### {label} — `{gap['location']}`")
                    lines.append("")
                    lines.append(gap["plain_english"])
                    lines.append("")
                    lines.append(f"**What is missing:** {gap['what_is_missing']}")
                    lines.append("")
                    lines.append(
                        f"**Consequence if not addressed:** {gap['consequence']}"
                    )
                    lines.append("")
                    lines.append(f"*VERBA term: {gap['verba_term']}*")
                    lines.append("")

        if dc_findings:
            lines.append("---")
            lines.append("")
            lines.append("## Failure mode candidates")
            lines.append("")
            for finding in dc_findings:
                lines.append(
                    f"### {finding['dc_code']} {finding['dc_name']} "
                    f"(Tier {finding['tier']})"
                )
                lines.append("")
                lines.append(f"**Location:** `{finding['location']}`")
                lines.append("")
                lines.append(finding["plain_english"])
                lines.append("")
                so = finding.get("stabiliser_recommendation", {})
                lines.append(
                    f"**Recommended operator:** "
                    f"{so.get('primary_so', '')} {so.get('so_name', '')}"
                )
                lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("## Governance score")
        lines.append("")
        gamma_str = str(gamma.get("proxy_value")) if gamma.get("proxy_value") is not None else "N/A"
        lines.append(f"**Structural Gamma proxy:** {gamma_str}")
        lines.append("")
        lines.append(gamma.get("interpretation", ""))
        lines.append("")
        lines.append(f"> {gamma.get('important_note', '')}")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Next steps")
        lines.append("")
        lines.append("1. Fill in the null fields in `.verba/governance.yaml`")
        lines.append("2. Complete the test stubs in `.verba/test_case_matrix.yaml`")
        lines.append("3. Open in Verba Studio for AI-assisted policy authoring")
        lines.append(
            "4. Add `x-verba qa . --schema .verba/governance.yaml` "
            "to your CI/CD pipeline (coming v0.2)"
        )
        lines.append("")
        lines.append(
            "*Generated by X-Verba — https://github.com/4vish/x-verba*"
        )

        return "\n".join(lines)
