"""
X-Verba Output Writer.

Generates the governance report in YAML, JSON, or Markdown.
Plain English first. VERBA term second. Always.
"""
import json
import yaml
from pathlib import Path
from datetime import datetime, timezone


class OutputWriter:
    """
    Writes scan results to the output format requested.

    The core principle: every VERBA term is introduced after
    the plain English explanation — never before it.
    """

    def __init__(self, results: dict, output_format: str = "yaml"):
        self.results = results
        self.format = output_format.lower()

    def write(self, output_path: str = None) -> str:
        """Write results to file and return the output path."""
        if not output_path:
            output_path = self._default_output_path()

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if self.format == "yaml":
            content = self._render_yaml()
        elif self.format == "json":
            content = self._render_json()
        elif self.format == "md":
            content = self._render_markdown()
        else:
            content = self._render_yaml()

        path.write_text(content, encoding="utf-8")
        return str(path)

    def _default_output_path(self) -> str:
        """Generate default output path based on format."""
        ext_map = {"yaml": "yaml", "json": "json", "md": "md"}
        ext = ext_map.get(self.format, "yaml")
        return f".verba/governance.{ext}"

    def _render_yaml(self) -> str:
        """Render the governance template as YAML with inline explanations."""
        lines = []

        lines.append("# ═══════════════════════════════════════════════════")
        lines.append("# X-VERBA GOVERNANCE REPORT")
        lines.append("# Generated by Super Semantics — https://supersemantic.ai")
        lines.append("#")
        lines.append("# HOW TO USE THIS FILE")
        lines.append("#")
        lines.append("# Every finding in this file has three parts:")
        lines.append("#   1. Plain English — what it means for your system")
        lines.append("#   2. Evidence — what X-Verba found in your code")
        lines.append("#   3. Policy field (~) — what YOU must define")
        lines.append("#")
        lines.append("# Fields marked ~ are governance decisions only you can make.")
        lines.append("# X-Verba gives you the structure. You provide the judgment.")
        lines.append("#")
        lines.append("# Open in Verba Studio for AI-assisted policy authoring.")
        lines.append("# ═══════════════════════════════════════════════════")
        lines.append("")

        meta = {
            "verba_version": self.results.get("verba_version", "1.0.0"),
            "scan_date": self.results.get("scan_date", ""),
            "repo": self.results.get("repo", ""),
            "identity_key": self.results.get("identity_key", ""),
            "reviewed": False,
            "approved": False,
        }
        lines.append(yaml.dump(meta, default_flow_style=False).strip())
        lines.append("")

        summary = self.results.get("summary", {})
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 1 — WHAT WE FOUND")
        lines.append("# A plain language summary of your system's governance state.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_summary_yaml(summary))

        primitives = self.results.get("primitives", {})
        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 2 — YOUR SYSTEM'S STATES")
        lines.append("#")
        lines.append("# A State is a precise snapshot of your system at a")
        lines.append("# specific moment. Every governance decision is a")
        lines.append("# function of the current State.")
        lines.append("#")
        lines.append("# ALLOWED STATE — the state your system is supposed")
        lines.append("# to be in. The intended outcome. The safe zone.")
        lines.append("#")
        lines.append("# INADMISSIBLE STATE — the state your system must")
        lines.append("# never reach. Not because it malfunctions — but")
        lines.append("# because it violates the rules you set.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_states_yaml(primitives))

        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 3 — WHERE YOUR SYSTEM NATURALLY DRIFTS")
        lines.append("#")
        lines.append("# A Drift Node is the natural destination of your")
        lines.append("# system when governance is absent. Not a bug. Not")
        lines.append("# a malfunction. A perfectly stable state that happens")
        lines.append("# to be one you never intended the system to reach.")
        lines.append("#")
        lines.append("# Your system is not broken. It is optimised.")
        lines.append("# The question is what it is optimised toward when")
        lines.append("# nothing governs it.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_drift_nodes_yaml(primitives))

        gaps = self.results.get("gaps", [])
        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 4 — MISSING CHECKPOINTS")
        lines.append("#")
        lines.append("# A Pre-Node is the last moment your system can be")
        lines.append("# stopped before it commits to an action.")
        lines.append("# After this point, the action happens.")
        lines.append("# Before this point, governance still has full control.")
        lines.append("#")
        lines.append("# Think of it as the difference between stopping a car")
        lines.append("# before it goes over a cliff versus trying to catch it")
        lines.append("# on the way down.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_gaps_yaml(gaps))

        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 5 — RULES THAT MUST ALWAYS HOLD")
        lines.append("#")
        lines.append("# An Invariant is a rule that must always be true —")
        lines.append("# across every state, every transition, every input.")
        lines.append("# No exceptions. Cannot be bypassed by automation.")
        lines.append("#")
        lines.append("# If violated, the system must stop immediately")
        lines.append("# and escalate to a human. Always.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_invariants_yaml(primitives))

        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 6 — LIMITS AND BOUNDARIES")
        lines.append("#")
        lines.append("# A Threshold is a fixed quantitative limit that")
        lines.append("# restricts what your system can do within a state.")
        lines.append("# Exceeding a Threshold invalidates the transition.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_thresholds_yaml(primitives))

        dc_findings = self.results.get("drift_classes", [])
        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 7 — FAILURE MODES IDENTIFIED")
        lines.append("#")
        lines.append("# Drift Classes are formally defined categories of")
        lines.append("# failure mode — like medical diagnosis codes.")
        lines.append("# A doctor does not say 'something is wrong.'")
        lines.append("# They say 'this is DC-L2, here is what causes it,")
        lines.append("# here is what it leads to, here is the treatment.'")
        lines.append("#")
        lines.append("# These are candidates — structural indicators that")
        lines.append("# suggest a failure mode may be present.")
        lines.append("# You review and confirm.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_dc_findings_yaml(dc_findings))

        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 8 — WHEN THE SYSTEM MUST STOP")
        lines.append("#")
        lines.append("# A Terminal State is a state from which no further")
        lines.append("# automated transitions are permitted.")
        lines.append("# Exit requires explicit, auditable human authorisation.")
        lines.append("# Automation cannot exit a Terminal State. Ever.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_terminal_states_yaml(gaps))

        gamma = self.results.get("structural_gamma", {})
        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 9 — GOVERNANCE SCORE")
        lines.append("#")
        lines.append("# Gamma is the central governance metric.")
        lines.append("# Gamma > 1.0 = your system tends toward safe outcomes.")
        lines.append("# Gamma < 1.0 = your Drift Node is the global minimum.")
        lines.append("#             Your system will find the unsafe outcome")
        lines.append("#             regardless of rule quality.")
        lines.append("#")
        lines.append("# NOTE: This is a structural proxy, not the runtime")
        lines.append("# metric. Runtime Gamma requires the VERBA Priming Engine.")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_gamma_yaml(gamma))

        lines.append("")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("# SECTION 10 — NEXT STEPS")
        lines.append("# ───────────────────────────────────────────────────")
        lines.append("")
        lines.append(self._render_next_steps_yaml(summary, gaps))

        return "\n".join(lines)

    def _render_summary_yaml(self, summary: dict) -> str:
        """Render plain-language executive summary."""
        ai_count = summary.get("ai_integrations_detected", 0)
        critical = summary.get("critical", 0)
        high = summary.get("high", 0)
        coverage = summary.get("governance_coverage", "0%")
        gamma = summary.get("structural_gamma", 0)
        files = summary.get("files_scanned", 0)

        if critical > 0:
            risk_level = "HIGH — this system has critical governance gaps"
        elif high > 0:
            risk_level = "MEDIUM — this system has high-severity gaps"
        else:
            risk_level = "LOW — no critical or high governance gaps detected"

        data = {
            "executive_summary": {
                "files_scanned": files,
                "ai_integrations_detected": ai_count,
                "governance_coverage": coverage,
                "structural_gamma_proxy": gamma,
                "risk_level": risk_level,
                "plain_language": (
                    f"X-Verba scanned {files} files and found "
                    f"{ai_count} AI integration points. "
                    f"{critical} critical and {high} high-severity "
                    f"governance gaps were detected. "
                    f"Governance coverage is currently {coverage}. "
                    f"The structural Gamma proxy is {gamma} — "
                    f"{'below' if gamma < 1.0 else 'at or above'} "
                    f"the governance sufficiency threshold of 1.0."
                )
            }
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_states_yaml(self, primitives: dict) -> str:
        """Render detected state structure."""
        nodes = primitives.get("nodes", [])
        ai_integrations = primitives.get("ai_integrations", [])

        states = []
        for i, ai in enumerate(ai_integrations, 1):
            states.append({
                f"state_{i:03d}": {
                    "location": ai["location"],
                    "type": "ai_governed_state",
                    "plain_english": (
                        "Your system is in an AI-governed state here — "
                        "it is about to call an AI model and use the "
                        "output to drive further behaviour."
                    ),
                    "allowed_state": {
                        "plain_english": (
                            "Define what staying within bounds looks like "
                            "at this state. What is the AI allowed to return? "
                            "What constitutes a valid, safe output?"
                        ),
                        "definition": None,
                    },
                    "inadmissible_state": {
                        "plain_english": (
                            "Define what must never happen at this state. "
                            "What output would violate your governance contract? "
                            "What would constitute a failure?"
                        ),
                        "detected_risk": (
                            "AI output flows from this call to a consequential "
                            "destination with no boundary check detected."
                        ),
                        "definition": None,
                    },
                    "pre_node_present": ai.get("pre_node_detected", False),
                    "human_review_present": ai.get("human_review_detected", False),
                }
            })

        data = {"system_states": states if states else [
            {
                "note": (
                    "No AI integration points detected. "
                    "Define your system states manually below."
                )
            }
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_drift_nodes_yaml(self, primitives: dict) -> str:
        """Render detected drift node candidates."""
        ai_integrations = primitives.get("ai_integrations", [])
        drift_nodes = []

        for i, ai in enumerate(ai_integrations, 1):
            drift_nodes.append({
                f"drift_node_{i:03d}": {
                    "location": ai["location"],
                    "provider": ai.get("provider", "unknown"),
                    "plain_english": (
                        "This AI call has no output boundary defined. "
                        "The model will naturally optimise toward being "
                        "helpful — which in your specific context may mean "
                        "crossing a boundary you intended to maintain."
                    ),
                    "what_the_system_drifts_toward": (
                        "Define what the natural drift direction is here. "
                        "What would this AI produce if left completely "
                        "ungoverned? That is your Drift Node."
                    ),
                    "governance_in_place": (
                        ai.get("pre_node_detected", False) and
                        ai.get("human_review_detected", False)
                    ),
                    "structural_risk_factors": {
                        "high_temperature": (
                            ai.get("temperature", 0) > 0.7
                            if ai.get("temperature") else False
                        ),
                        "dynamic_prompt": ai.get("dynamic_prompt", False),
                        "user_input_in_prompt": ai.get("user_input_in_prompt", False),
                        "no_pre_node": not ai.get("pre_node_detected", False),
                        "no_human_review": not ai.get("human_review_detected", False),
                    },
                    "allowed_node_definition": None,
                    "drift_node_definition": None,
                }
            })

        data = {"drift_nodes": drift_nodes if drift_nodes else [
            {"note": "No drift nodes detected."}
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_gaps_yaml(self, gaps: list) -> str:
        """Render governance gaps — Pre-Nodes, human gates, invariants."""
        gap_data = []
        for gap in gaps:
            gap_data.append({
                gap["id"]: {
                    "location": gap["location"],
                    "severity": gap["severity"],
                    "plain_english": gap["plain_english"],
                    "what_is_missing": gap["what_is_missing"],
                    "consequence_if_not_addressed": gap["consequence"],
                    "governance_term": gap["verba_term"],
                    "governance_explanation": gap["verba_explanation"],
                    "recommended_action": gap["recommended_action"],
                    "policy": None,
                    "severity_confirmed": None,
                    "terminal_state_required": (
                        gap["severity"] == "critical"
                    ),
                    "governance_authority": None,
                }
            })

        data = {"governance_gaps": gap_data if gap_data else [
            {"note": "No governance gaps detected. Run x-verba qa to verify."}
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_invariants_yaml(self, primitives: dict) -> str:
        """Render detected informal invariants needing formalisation."""
        constraints = primitives.get("constraints", [])
        invariant_data = []

        for i, c in enumerate(constraints, 1):
            invariant_data.append({
                f"INV-{i:03d}": {
                    "location": c["location"],
                    "detected_from": "existing_validation_in_code",
                    "current_form": c["line_content"],
                    "constraint_type": c["type"],
                    "near_ai_call": c.get("near_ai_call", False),
                    "plain_english": (
                        "A governance check exists here in your code. "
                        "Your developer already understood that something "
                        "should be validated at this point. "
                        "X-Verba has detected it as a candidate Invariant."
                    ),
                    "what_formalising_means": (
                        "Formalising this check means it becomes a declared "
                        "governance rule — version-controlled, machine-executable, "
                        "and connected to the audit trail. A future developer "
                        "cannot remove it without the governance system flagging "
                        "the regression."
                    ),
                    "consequence_if_removed": (
                        "This check disappears silently. No test catches it. "
                        "No audit records it. The governance was informal "
                        "and is now gone."
                    ),
                    "currently_enforced": True,
                    "currently_formalised": False,
                    "formal_definition": None,
                    "severity": None,
                    "violation_action": None,
                    "cannot_be_bypassed": None,
                }
            })

        data = {"candidate_invariants": invariant_data if invariant_data else [
            {
                "note": (
                    "No informal invariants detected. "
                    "Define your Invariants below — rules that must "
                    "always hold across all states."
                )
            }
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_thresholds_yaml(self, primitives: dict) -> str:
        """Render detected thresholds and boundary conditions."""
        ai_integrations = primitives.get("ai_integrations", [])
        threshold_data = []

        for i, ai in enumerate(ai_integrations, 1):
            temp = ai.get("temperature")
            max_tokens = ai.get("max_tokens")

            if temp is not None or max_tokens is not None:
                threshold_data.append({
                    f"TH-{i:03d}": {
                        "location": ai["location"],
                        "plain_english": (
                            "Model parameters detected at this AI call. "
                            "These parameters directly affect output "
                            "variability and must be governed explicitly."
                        ),
                        "detected_parameters": {
                            "temperature": temp,
                            "temperature_assessment": (
                                f"HIGH — temperature {temp} increases output "
                                f"variability significantly. Governance cost "
                                f"increases with higher temperature."
                                if temp and temp > 0.7
                                else f"Within acceptable range ({temp})"
                                if temp else "Not detected"
                            ),
                            "max_tokens": max_tokens,
                            "max_tokens_assessment": (
                                "No explicit output length limit detected. "
                                "Unbounded output length is a governance gap."
                                if not max_tokens
                                else f"Output length limited to {max_tokens} tokens"
                            ),
                        },
                        "recommended_thresholds": {
                            "maximum_temperature": 0.3,
                            "temperature_note": (
                                "Lower temperature = more deterministic output = "
                                "easier to govern. For high-stakes contexts, "
                                "temperature should not exceed 0.3."
                            ),
                            "maximum_output_tokens": None,
                            "minimum_confidence_score": None,
                            "forbidden_content_patterns": None,
                        },
                    }
                })

        data = {"thresholds": threshold_data if threshold_data else [
            {
                "note": (
                    "No AI model parameters detected. "
                    "Define your Thresholds below."
                )
            }
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_dc_findings_yaml(self, dc_findings: list) -> str:
        """Render Drift Class findings with full plain-language explanations."""
        finding_data = []

        for i, finding in enumerate(dc_findings, 1):
            contraindications = finding.get(
                "stabiliser_recommendation", {}
            ).get("contraindications", [])

            finding_data.append({
                f"DC-FINDING-{i:03d}": {
                    "code": finding["dc_code"],
                    "name": finding["dc_name"],
                    "tier": finding["tier"],
                    "tier_meaning": self._get_tier_meaning(finding["tier"]),
                    "location": finding["location"],
                    "severity": finding["severity"],
                    "plain_english": finding["plain_english"],
                    "what_happens_without_governance": finding.get(
                        "what_happens_without_governance", ""
                    ),
                    "consequence": finding.get("consequence", ""),
                    "evidence_detected": finding["evidence"],
                    "legion_detected": {
                        "code": finding["legion_detected"]["code"],
                        "name": finding["legion_detected"]["name"],
                        "what_this_legion_means": finding["legion_detected"]["description"],
                    },
                    "stabiliser_recommendation": {
                        "apply": finding["stabiliser_recommendation"]["primary_so"],
                        "name": finding["stabiliser_recommendation"]["so_name"],
                        "plain_english": finding["stabiliser_recommendation"]["plain_english"],
                        "contraindications": [
                            {
                                "do_not_apply": c.get("do_not_apply", ""),
                                "reason": c.get("reason", ""),
                            }
                            for c in contraindications
                        ] if contraindications else "None for this DC class",
                    },
                    "monitoring_frequency": finding["monitoring_frequency"],
                    "human_review_required": True,
                    "confirmed": None,
                    "policy": None,
                    "invariant_ref": None,
                    "terminal_state_ref": None,
                }
            })

        data = {"drift_class_findings": finding_data if finding_data else [
            {"note": "No Drift Class candidates detected."}
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_terminal_states_yaml(self, gaps: list) -> str:
        """Render required Terminal State definitions."""
        critical_gaps = [g for g in gaps if g.get("severity") == "critical"]
        ts_data = []

        for i, gap in enumerate(critical_gaps, 1):
            ts_data.append({
                f"TS-{i:03d}": {
                    "triggered_by_gap": gap["id"],
                    "location": gap["location"],
                    "plain_english": (
                        "A Terminal State is where automation stops and "
                        "a human takes over. No automated path exits a "
                        "Terminal State. Only an explicit, auditable human "
                        "decision can resume processing."
                    ),
                    "why_needed_here": gap["plain_english"],
                    "real_world_example": (
                        "The 2003 Northeast Blackout: the alarm system "
                        "entered a failure state at 14:14. No Terminal State "
                        "fired. No human was notified. The cascade committed "
                        "at 16:10. 116 minutes and 55 million people without "
                        "power. A single Invariant monitoring the alarm "
                        "system's heartbeat would have caught it at 14:14."
                    ),
                    "entry_conditions": None,
                    "automated_transitions": "NONE — by definition",
                    "governance_authority": None,
                    "human_authorised_transition_required": True,
                    "re_enablement_creates_new_instance": True,
                    "escalation_path": None,
                    "response_time_sla": None,
                }
            })

        data = {"terminal_states": ts_data if ts_data else [
            {
                "note": (
                    "No critical gaps detected requiring Terminal States. "
                    "Define Terminal States below for any condition where "
                    "automation must stop and a human must decide."
                )
            }
        ]}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_gamma_yaml(self, gamma: dict) -> str:
        """Render structural Gamma proxy with full explanation."""
        data = {
            "structural_gamma": {
                "proxy_value": gamma.get("proxy_value", 0),
                "threshold": gamma.get("threshold", 1.0),
                "robust_threshold": gamma.get("robust_threshold", 1.1),
                "status": gamma.get("status", "UNKNOWN"),
                "plain_english_interpretation": gamma.get("interpretation", ""),
                "what_gamma_means": gamma.get("what_this_means", ""),
                "important_note": gamma.get("important_note", ""),
                "delta_proxy": gamma.get("delta_proxy", 0),
                "energy_gap_proxy": gamma.get("energy_gap_proxy", 0),
            }
        }
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _render_next_steps_yaml(
        self, summary: dict, gaps: list
    ) -> str:
        """Render prioritised next steps."""
        critical = summary.get("critical", 0)
        high = summary.get("high", 0)

        steps = [
            {
                "step_1": {
                    "action": "Review every critical finding above",
                    "why": (
                        "Critical findings are the governance gaps that pose "
                        "the highest immediate risk. Start here."
                    ),
                    "how": (
                        "Read the plain_english field for each critical gap. "
                        "Understand what is missing and what the consequence is. "
                        "Fill in the policy field for each one."
                    ),
                    "critical_count": critical,
                }
            },
            {
                "step_2": {
                    "action": "Fill in every field marked null",
                    "why": (
                        "Each null field is a governance decision only you "
                        "can make. VERBA gives you the structure. "
                        "You provide the judgment."
                    ),
                    "how": (
                        "Write plain language first. What must this system "
                        "never do? What must always be true? Who is the "
                        "Governance Authority? Verba Studio will help you "
                        "translate plain language into formal policy."
                    ),
                }
            },
            {
                "step_3": {
                    "action": "Open in Verba Studio",
                    "why": (
                        "The AI assistant in Verba Studio explains every "
                        "finding in the context of your specific system, "
                        "helps you write policies, and validates your "
                        "governance contract before it is compiled."
                    ),
                    "url": "https://studio.supersemantic.ai",
                }
            },
            {
                "step_4": {
                    "action": "Add x-verba qa to your CI/CD pipeline",
                    "why": (
                        "Every future code change is automatically checked "
                        "against this governance contract. Governance "
                        "regressions are caught before they ship."
                    ),
                    "command": (
                        "x-verba qa . --schema .verba/governance.yaml"
                    ),
                    "ci_note": (
                        "Returns exit code 1 if critical regressions found. "
                        "Integrate as a pipeline step after your test suite."
                    ),
                }
            },
            {
                "step_5": {
                    "action": "Compile and deploy with VERBA Runtime",
                    "why": (
                        "When your schema is complete, verba compile turns "
                        "it into a machine-executable governance bundle. "
                        "The Priming Engine loads it and begins monitoring. "
                        "The Ledger begins recording. Governance becomes "
                        "provable, not claimed."
                    ),
                    "command": "x-verba compile .verba/governance.yaml",
                }
            },
        ]

        data = {"next_steps": steps}
        return yaml.dump(data, default_flow_style=False, allow_unicode=True)

    def _get_tier_meaning(self, tier: str) -> str:
        """Get plain-language tier meaning."""
        meanings = {
            "A": "Well evidenced — multiple documented real-world instances",
            "B": "Theoretically grounded — derived from established theory",
            "C": "Hypothesised — proposed by analogy, no current empirical validation",
            "D": "Limit class — may represent a fundamental limit not fully addressable",
        }
        return meanings.get(tier, "Unknown tier")

    def _render_json(self) -> str:
        """Render results as structured JSON."""
        return json.dumps(self.results, indent=2, default=str)

    def _render_markdown(self) -> str:
        """Render results as a human-readable markdown report."""
        lines = []
        summary = self.results.get("summary", {})
        gaps = self.results.get("gaps", [])
        dc_findings = self.results.get("drift_classes", [])
        gamma = self.results.get("structural_gamma", {})

        lines.append("# X-Verba Governance Report")
        lines.append(
            f"*Generated {self.results.get('scan_date', '')} "
            f"by Super Semantics*"
        )
        lines.append("")
        lines.append(
            f"**Repository:** `{self.results.get('repo', '')}`  "
        )
        lines.append(
            f"**Identity Key:** `{self.results.get('identity_key', '')}`"
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## What we found")
        lines.append("")
        lines.append(
            f"X-Verba scanned **{summary.get('files_scanned', 0)} files** "
            f"and found **{summary.get('ai_integrations_detected', 0)} "
            f"AI integration points**."
        )
        lines.append("")

        critical = summary.get("critical", 0)
        high = summary.get("high", 0)
        coverage = summary.get("governance_coverage", "0%")
        gamma_val = summary.get("structural_gamma", 0)

        lines.append(
            f"| Metric | Value |"
        )
        lines.append("| --- | --- |")
        lines.append(f"| Critical findings | **{critical}** |")
        lines.append(f"| High findings | {high} |")
        lines.append(f"| Governance coverage | {coverage} |")
        lines.append(
            f"| Structural Gamma proxy | {gamma_val} "
            f"({'below threshold' if gamma_val < 1.0 else 'at threshold'}) |"
        )
        lines.append("")

        if critical > 0 or high > 0:
            lines.append("---")
            lines.append("")
            lines.append("## Critical findings")
            lines.append("")
            for gap in gaps:
                if gap.get("severity") in ["critical", "high"]:
                    severity_label = (
                        "🔴 CRITICAL" if gap["severity"] == "critical"
                        else "🟡 HIGH"
                    )
                    lines.append(
                        f"### {severity_label} — `{gap['location']}`"
                    )
                    lines.append("")
                    lines.append(gap["plain_english"])
                    lines.append("")
                    lines.append(
                        f"**What is missing:** {gap['what_is_missing']}"
                    )
                    lines.append("")
                    lines.append(
                        f"**Consequence if not addressed:** {gap['consequence']}"
                    )
                    lines.append("")
                    lines.append(
                        f"*Governance term: {gap['verba_term']}*"
                    )
                    lines.append("")

        if dc_findings:
            lines.append("---")
            lines.append("")
            lines.append("## Failure modes identified")
            lines.append("")
            for finding in dc_findings:
                lines.append(
                    f"### {finding['dc_code']} {finding['dc_name']} "
                    f"(Tier {finding['tier']})"
                )
                lines.append("")
                lines.append(f"**Location:** `{finding['location']}`")
                lines.append("")
                lines.append(finding["plain_english"])
                lines.append("")
                lines.append(
                    f"**What happens without governance:** "
                    f"{finding.get('what_happens_without_governance', '')}"
                )
                lines.append("")
                so = finding.get("stabiliser_recommendation", {})
                lines.append(
                    f"**Recommended operator:** "
                    f"{so.get('primary_so', '')} {so.get('so_name', '')}  "
                )
                lines.append(so.get("plain_english", ""))
                lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("## Governance score")
        lines.append("")
        lines.append(
            f"**Structural Gamma proxy:** {gamma.get('proxy_value', 0)}"
        )
        lines.append("")
        lines.append(gamma.get("interpretation", ""))
        lines.append("")
        lines.append(f"> {gamma.get('important_note', '')}")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Next steps")
        lines.append("")
        lines.append(
            "1. Fill in the policy fields in `.verba/governance.yaml`"
        )
        lines.append("2. Open in Verba Studio for AI-assisted authoring")
        lines.append(
            "3. Add `x-verba qa . --schema .verba/governance.yaml` "
            "to your CI/CD pipeline"
        )
        lines.append(
            "4. Run `x-verba compile .verba/governance.yaml` "
            "when schema is approved"
        )
        lines.append("")
        lines.append(
            "*Generated by X-Verba — "
            "https://github.com/4vish/x-verba*"
        )

        return "\n".join(lines)
